### ISSUE TITLE
Add `warningOnStdErr` boolean property on the Airbyte sync task to allow marking the task as Successful despite warnings

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-airbyte#35]
### Feature description

Currently, if the sync emits warnings, the task ends with Warnings, even when those warnings are insignificant 

![image](https://github.com/kestra-io/plugin-airbyte/assets/86264395/99509618-a30c-4d02-8700-854da1d5db6f)

![image](https://github.com/kestra-io/plugin-airbyte/assets/86264395/6549d263-5153-4460-b222-2905a15a1378)

We should consider adding this line conditionally based on the new property https://github.com/kestra-io/plugin-airbyte/blob/fcd17dec6dc05dff8cd48ec02c313264f0c924d7/src/main/java/io/kestra/plugin/airbyte/connections/Sync.java#L210

**Comment by aballiet** [comment]
Fixed in PR : https://github.com/kestra-io/plugin-airbyte/pull/38. 
Remove logger warning : https://github.com/kestra-io/plugin-airbyte/pull/38
