### ISSUE TITLE
Add `failOnActiveSync` boolean property

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-airbyte#44]
### Feature description

This will allow us to fail (or not) the task run when the Airbyte sync raises `A sync is already running for: b40d5dd4-f875-40a6-90de-034f2687cd8e`

This property can be by default set to true

Resuming the task execution after that error can be handled with retries.

**Comment by aballiet** [comment]
We might need to output something like `syncState` which could be `RUNNING`, `ALREADY_RUNNING`

=> to be able to make decision on the fact that the sync is already running : wether user want to perform remaining tasks or not 👍
